base_config: showo_finetune_scene_base.yaml

experiment:
    name: showo_finetune_omomo
    output_dir: "${oc.env:FULL_DIR,exp/showo_finetune_omomo}"
    train_selected_dataset: OMOMO
    eval_selected_dataset: OMOMO
    full_eval_datasets:
        - {name: OMOMO, root: "${oc.env:OMOMO_ROOT,data/processed/omomo/v1}", sample_num: null}
    max_train_imu_len: 240

dataset:
    params:
        imu_path_or_url: "${oc.env:OMOMO_ROOT,data/processed/omomo/v1}"
        train_imu_paths_or_urls:
            - "${oc.env:OMOMO_ROOT,data/processed/omomo/v1}"
        train_imu_source_weights: []

training:
    max_train_steps: 1000
